name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim: [v0.9.5, stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}
      - name: Load colorscheme
        run: nvim --headless --clean --cmd "set rtp+=." -l tests/smoke.lua
